#!/usr/bin/bash
# A simple databases management system using Bash Shell
echo welcome to DBMS
# Directory to store databases
DataBase="databases"
create_database() {
    echo -n "Enter database name: "
    read dbname
    if [[ -z "$DataBase" ]]
     then
        echo "Database name cannot be empty!"
        return
    fi
    if [[ -d "$DataBase/$dbname" ]]
     then
        echo "Database '$dbname' already exists!"
    else
        mkdir -p "$DataBase/$dbname"
        echo "Database '$dbname' created successfully!"
    fi
}

