#!/bin/bash

isInt() {
    if ! [[ $1 =~ ^[0-9]+$ ]]; then
        zenity --warning --text="Please Enter Valid Integer"
        return 1
    else
        return 0
    fi
}

isChar() {
    if ! [[ ${1^^} =~ ^[A-Z0-9\ _]+$ ]]; then
        zenity --warning --text="Please Enter Valid Name"
        return 1
    else
        return 0
    fi
}

isEmpty() {

    if [[ $1 =~ ^[" "]+$ || -z $1 ]]; then
        zenity --warning --text="Please Enter Valid Name"
        return 1
    else
        return 0
    fi
}