#!/bin/bash
create_table() {
    Tb_name=$(zenity --entry --text="Please Enter Table Name")
                		if [[ -z $Tb_name || $Tb_name =~ ^[" "]+$ ]]
                		then
                			zenity --error --text="Table Name Can't be Empty"
                            return
                		fi
                		if [[ -e $Tb_name ]]
                		then
                			zenity --error --text="Table already Exists"
                		else
                			while true
                			do
                			col_num=$(zenity --entry --text="Please Enter Columns Numbers")
                			isInt $col_num
                			if [[ $? -eq 0 ]]
                			then
                				break
                			else
                				continue
                			fi
                			done
                			flag=0
                			for((i=0;i<$col_num;i++))
                			do
		        			line=""
		        			while true
		        			do
		        			colname=$(zenity --entry --text="Please enter column $((i+1)) Name")
                            if [[ $(cat .$Tb_name-metadata 2> /dev/null | cut -d: -f1 | grep -w $colname 2> /dev/null) ]]
                            then
                                zenity --error --text="Column $colname already exists"
                                continue
                            fi
		        			if [[ -z $colname || $colname =~ ^[" "]+$ ]]
		        			then
		        				zenity --warning --text="Column Name Can't be Empty"
		        				continue
		        			fi
		        			isChar $colname
		        			if [[ $? -eq 0 ]]
		        			then
		        				zenity --notification --text="Column $colname Created"
		        				line+=$colname:
		        				break
		        			else
		        				continue
		        			fi
		        			done
		        			while true
		        			do
		        			col_data=$(zenity --entry --text="Please Enter Data Type (int-char)")
		        			if [[ -z $col_data ]]
		        			then
		        				zenity --warning --text="Column Datatype Can't be Empty"
		        				continue
		        			fi
		        			if ! [[ ${col_data^^} =~ ^(CHAR|INT)$ ]]
		        			then
		        				zenity --warning --text="Allowed Data types (int - char)"
		        				continue 
                				else
                					line+=$col_data:
                					break
                				fi
                				done
                				if [[ $flag -eq 0 ]]
						then
							if $(zenity --question --text="Do you want $col_name to be primary key ?")
							then
							line+=pk
							flag=1
							fi
				fi
				echo $line >> .$Tb_name-metadata
                			done
                			touch $Tb_name
                			zenity --notification --text="Table $Tb_name created"
                		fi
}

drop_table() {
    Tb_name=$(zenity --entry --text="Please Enter Table Name")
                		if [[ -z $Tb_name || $Tb_name =~ ^[" "]+$ ]]
                		then
                			zenity --error --text="Table Name Can't be Empty"
                		else
                			if [[ -e $Tb_name ]]
                			then
                				rm $Tb_name
                				rm .$Tb_name-metadata
                				zenity --notification --text="Table $Tb_name Dropped"
                			else
                				zenity --error --text="Table $Tb_name doesn't exist"
                			fi
                		fi
}


select_from_table() {

    Tb_name=$(zenity --entry --text="Please Enter Table Name")
                		if [[ -z $Tb_name || $Tb_name =~ ^[" "]+$ ]]
                		then
                			zenity --error --text="Table Name Can't be Empty"
                		else
                			if [[ -e $Tb_name ]]
                			then
                				zenity --notification --text="Table $Tb_name Selected"
                				columns=$(awk -F: '{print $1}' .$Tb_name-metadata)
                                
                			else
                				zenity --error --text="Table $Tb_name doesn't exist"
                			fi
                		fi
}